name: Clang Format Github Action
author: Rafik Farhad <rafikfarhad@gmail.com>
description: An action that check the code format is compliant with a certain configuration
branding:
  icon: feather
  color: gray-dark
inputs:
  style:
    description: The style to use by clang-format. 
    required: false
    default: 'LLVM'
  sources:
    description: |
      Location of sources to check. It can be a single file,
      regex of a directory, or multiple selectors separated 
      by comma (`,`)
    required: false
    default: "**/*"
  excludes:
    description: |
      Paths to exclude separated by comma (`,`)
    required: false
    default: ""
outputs:
  clang-format-version:
    description: The version of clang-format used by this action
runs:
  using: docker
  image: Dockerfile
